{{- $tenants := include "tenants" $ | fromYaml -}}
{{- range $tenantId, $tenant := $tenants -}}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ $tenantId }}
  # namespace: argocd
---
{{- end -}}
