{{- $tenants := include "tenants" $ | fromYaml -}}
{{- range $tenantId, $tenant := $tenants -}}
{{- with .namespace -}}
{{- if .enabled -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $tenantId }}
  {{- with .annotations }}
  annotations: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .labels }}
  labels: {{- . | toYaml | nindent 4 }}
  {{- end }}
---
{{- end -}}
{{- end -}}
{{- end -}}
