{{- $tenants := include "tenants" $ | fromYaml -}}
{{- range $tenantId, $tenant := $tenants -}}
{{- range $namespaceId, $namespace := .namespaces -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $namespaceId }}
  {{- with .annotations }}
  annotations: {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .labels }}
  labels: {{- . | toYaml | nindent 4 }}
  {{- end }}
---
{{- end -}}
{{- end -}}
