applicationDefaults:
  name: ""
  argoNamespace: argocd
  labels:
    is-cool: true
  annotations:
    is-cool: true
  deletion:
    cascade: true
    propagationPolicy: foreground|background

# One AppProject per tenant
# N namespaces
  # One limit range per
  # One Resource quota per
  # Network policies per
# RBAC too
tenants:
  platform:
    enabled: true
    # quota: {}
    namespaces:
      argocd: {}
    applications:
      argocd:

