

# One AppProject per tenant
# N namespaces
  # One limit range per
  # One Resource quota per
  # Network policies per
# RBAC too
tenants:
  platform:
    enabled: true
    # quota: {}
    namespaces:
      argocd: {}
    applications: {}
